version: '3.8'
services:
  api:
    build:
      context: .
    volumes:
      - .:/app  # Monta el directorio actual en /app
    working_dir: /app  # Establece el directorio de trabajo en /app
    ports:
      - "5000:5000"  # Mapea el puerto 5000
    environment:
      FLASK_ENV: development
      MONGO_URI: mongodb://mongo:27017/mac_store  # URI de conexión a MongoDB
      REDIS_HOST: redis  # Host para Redis
    command: python main.py  # Ejecuta el archivo main.py
    depends_on:
      - mongo  # Asegúrate de que MongoDB esté corriendo
      - redis  # Asegúrate de que Redis esté corriendo

  mongo:
    image: mongo:6.0  # Usa la imagen de MongoDB
    ports:
      - "27017:27017"  # Mapea el puerto 27017
    volumes:
      - mongo_data:/data/db  # Volumen para persistir datos de MongoDB

  redis:
    image: redis:7.0  # Usa la imagen de Redis
    ports:
      - "6379:6379"  # Mapea el puerto 6379

volumes:
  mongo_data:  # Define un volumen para MongoDB
